config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'posts#index'
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: :show
  resources :worrys, only: :index
  resources :skills, only: :index
  resources :foreigns, only: :index
  resources :inquirys, only: :index
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true , length: {maximum: 40}

  has_rich_text :content
  belongs_to :user

  has_many :comments

  enum genre: { worry: 0, skill: 1, foreign: 2 }

  validate :validate_content_attachment_byte_size
  validate :validate_content_attachments_count

  ONE_KILOBYTE = 1024
  MAX_MEGA_BYTES = 0.5
  MAX_CONTENT_ATTACHMENT_BYTE_SIZE = MAX_MEGA_BYTES * 1_000 * ONE_KILOBYTE
  MAX_CONTENT_ATTACHMENTS_COUNT = 2

  private

  def validate_content_attachment_byte_size
    content.body.attachables.grep(ActiveStorage::Blob).each do |attachable|
      if attachable.byte_size > MAX_CONTENT_ATTACHMENT_BYTE_SIZE
        errors.add(
          :base,
          :content_attachment_byte_size_is_too_big,
          max_content_attachment_mega_byte_size: MAX_MEGA_BYTES,
          bytes: attachable.byte_size,
          max_bytes: MAX_CONTENT_ATTACHMENT_BYTE_SIZE
        )
      end
    end  
  end

  def validate_content_attachments_count
    if content.body.attachables.grep(ActiveStorage::Blob).count > MAX_CONTENT_ATTACHMENTS_COUNT
      errors.add(
        :content,
        :attachments_count_is_too_big,
        max_content_attachments_count: MAX_CONTENT_ATTACHMENTS_COUNT
      )
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    if comment.save
      redirect_to "/posts/#{comment.post.id}",  notice: 'コメントを投稿しました。'
    else
      redirect_to "/posts/#{comment.post.id}",  notice: 'コメントを投稿できませんでした'
    end
  end

  def destroy
    comment = Comment.find(params[:post_id])
    comment.destroy
    redirect_to "/posts/#{comment.post.id}",  notice: 'コメントを削除しました。'
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/foreigns_controller.rb
class ForeignsController < ApplicationController
  def index
    @posts = Post.where(genre: 2).order("created_at DESC").page(params[:page]).per(20)
  end
end

app/controllers/inquirys_controller.rb
class InquirysController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, except: [:index, :show]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(12)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: '記事を投稿しました。' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: '記事を更新しました。' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: '記事を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :genre, :content).merge(user_id: current_user.id)
    end

    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @posts = Post.where(genre: 1).order("created_at DESC").page(params[:page]).per(20)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @posts = user.posts
    @comments = user.comments
  end
end

app/controllers/worrys_controller.rb
class WorrysController < ApplicationController
  def index
    @posts = Post.where(genre: 0).order("created_at DESC").page(params[:page]).per(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foreigns_helper.rb
module ForeignsHelper
end

app/helpers/inquirys_helper.rb
module InquirysHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/worrys_helper.rb
module WorrysHelper
end

app/views/foreigns/index.html.erb
<div class="post-contents">
  <h1>技能実習生関連</h1>
  <p>このページではすべての投稿から、ジャンルが「技能実習生」だけを表示しています。</p>
  <%= render partial: 'shared/index', locals: { posts: @posts}%>
  <div class="post-contents__post-paginate">
    <%= paginate(@posts) %>
  </div>
</div>

app/views/inquirys/index.html.erb
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdejWHTxWg26k0miJxxBcZdnnTZqas08IOPO05UIB0S3orlkg/viewform?embedded=true" width="640" height="1200" frameborder="0" marginheight="0" marginwidth="0">読み込んでいます…</iframe>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <div class="error-box">
    <% if post.errors.any? %>
      <div id="error_explanation" class="top-notice">
        <h2><%= pluralize(post.errors.count, "エラー！") %> 保存できていません。再トライしてください。</h2>
  
        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="form-group form-title">
    <%= form.label :title  %>
    <%= form.text_field :title %>
  </div>

  <div class="form-group">
    <%= form.label :genre %>
    <%= form.select :genre, Post.genres_i18n.invert, {}, placeholder: 0  %>
  </div>

  <div class="form-group">
    <%= form.rich_text_area :content %>
  </div>

  <div class="form-group">
    <%= form.submit "投稿" , class: "btn btn-primary rounded-pill"%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>編集ページ</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<div class="top-box">
  <div class="top-box__top-title">
    <h1>介護お悩み掲示板</h1>
  </div>
  <div class="top-box__top-explain">
    <p>この掲示板は、介護に悩みがある人の悩みや愚痴を言い合う掲示板です。３つのジャンル「介護お悩み掲示板」、「スキルアップ・転職」、「技能実習生関連」に分かれています。画面左上のメニューから各ページを見れるようになってます。ご利用にあたっては、閲覧だけならは会員登録せずみれます。会員登録すると、記事の投稿・コメント投稿ができるようになります。会員登録した情報は、ログインユーザーの識別のためだけの利用で、第３者に個人情報を渡すようなことはありません。投稿する際は、他人が不快に思う記事や介護・福祉に関係ない記事はご遠慮ください。管理人が不適切とみなした場合は、削除させていただきます。</p>
  </div>
</div>

<hr>


<div class="post-contents">
  <%= render partial: 'shared/index', locals: { posts: @posts}%>
  <div class="post-contents__post-paginate">
    <%= paginate(@posts) %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>記事を投稿</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="show-contents">
  <div class="post-box">
    <div class="post-box__post-title"><h4><%= @post.title %></h2></div>
    <div class="post-box__post-id">ID：<%= @post.id %></div>
    <div class="post-box__post-name">投稿者：<%= @post.user.nickname %></div>
    <div class="post-box__post-name">ジャンル：<%= @post.genre_i18n %></div>
    <div class="post-box__post-name">投稿日時：<%= @post.created_at.strftime("%Y/%m/%d %H:%M") %></div>
    <% if user_signed_in? && current_user.id == @post.user_id %>
      <div class="post-box__post-delete"><%= link_to '投稿削除', post_path(@post.id), method: :delete, data: { confirm: '本当にコメントを削除してもよろしいでしょうか?' } %></div>
      <div class="post-box__post-edit"><%= link_to '編集', edit_post_path(@post) %></div>
    <% end %>  
    <div class="post-box__post-text"><%= @post.content %></div>
  </div>
  <div class="comment-box">
    <h2>コメント</h2>
    <div class="comment-box__comment-submit">
      <% if current_user %>
        <%= form_with(model: [@post, @comment], local: true) do |form| %>
          <div class="form-group">
            <%= form.text_area :text, placeholder: "ここにコメントを入力してください", rows: "5", class: "form-control" %>
          </div>
          <%= form.submit "投稿" , class: "btn btn-primary rounded-pill"%>
        <% end %>
      <% else %>
        <p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p>
      <% end %>
    </div>
    <div class="comment-box__comment-posted">
      <% if @comments %>
        <% @comments.each do |comment| %>
          <div class="comment-box__comment-posted__comment-each">
            <div class="comment-box__comment-posted__comment-each--name">名前：<%= comment.user.nickname %>
            <% if user_signed_in? && current_user.id == comment.user_id %>
              <%= link_to 'コメント削除', post_comment_path(comment), method: :delete, data: { confirm: '本当にコメントを削除してもよろしいでしょうか?' } %>
            <% end %>
            </div>
            <div class="comment-box__comment-posted__comment-each--date">投稿日時：<%= comment.created_at.strftime("%Y/%m/%d %H:%M") %>
            </div>
            <div class="comment-box__comment-posted__comment-each--text"><%= comment.text %></div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/skills/index.html.erb
<div class="post-contents">
  <h1>スキルアップ・転職</h1>
  <p>このページではすべての投稿から、ジャンルが「スキルアップ・転職」だけを表示しています。</p>
  <%= render partial: 'shared/index', locals: { posts: @posts}%>
  <div class="post-contents__post-paginate">
    <%= paginate(@posts) %>
  </div>
</div>

app/views/users/show.html.erb
<div class="mypage">
  <h2><%= @nickname %>さんのマイページ</h2>
  <div class="mypage__mypage-name">
    投稿一覧
  </div>
  <div class="mypage__mypage-posts">
    <% @posts.each do |post| %>
      <div class="mypage__mypage-posts__mypage-each">
        <%= link_to "#{post.title}", post %>
      </div>
    <% end %>
  </div>

  <hr>
  <div class="mypage__mypage-name">
    コメント一覧
  </div>
  <div class="mypage__mypage-posts">
    <% @comments.each do |comment| %>
      <div class="mypage__mypage-posts__mypage-each">
        <%= link_to "#{comment.text}", post_path(comment.post_id)  %>
      </div>
    <% end %>
  </div>
</div>

app/views/worrys/index.html.erb
<div class="post-contents">
  <h1>介護お悩み</h1>
  <p>このページではすべての投稿から、ジャンルが「介護お悩み」だけを表示しています。</p>
  <%= render partial: 'shared/index', locals: { posts: @posts}%>
  <div class="post-contents__post-paginate">
    <%= paginate(@posts) %>
  </div>
</div>