config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'posts#index'
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: :show
  resources :worrys, only: :index
  resources :skills, only: :index
  resources :foreigns, only: :index
  resources :inquirys, only: :index
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true , length: {maximum: 40}

  has_rich_text :content
  belongs_to :user

  has_many :comments

  enum genre: { worry: 0, skill: 1, foreign: 2 }

  validate :validate_content_attachment_byte_size
  validate :validate_content_attachments_count

  ONE_KILOBYTE = 1024
  MAX_MEGA_BYTES = 0.5
  MAX_CONTENT_ATTACHMENT_BYTE_SIZE = MAX_MEGA_BYTES * 1_000 * ONE_KILOBYTE
  MAX_CONTENT_ATTACHMENTS_COUNT = 2

  private

  def validate_content_attachment_byte_size
    content.body.attachables.grep(ActiveStorage::Blob).each do |attachable|
      if attachable.byte_size > MAX_CONTENT_ATTACHMENT_BYTE_SIZE
        errors.add(
          :base,
          :content_attachment_byte_size_is_too_big,
          max_content_attachment_mega_byte_size: MAX_MEGA_BYTES,
          bytes: attachable.byte_size,
          max_bytes: MAX_CONTENT_ATTACHMENT_BYTE_SIZE
        )
      end
    end  
  end

  def validate_content_attachments_count
    if content.body.attachables.grep(ActiveStorage::Blob).count > MAX_CONTENT_ATTACHMENTS_COUNT
      errors.add(
        :content,
        :attachments_count_is_too_big,
        max_content_attachments_count: MAX_CONTENT_ATTACHMENTS_COUNT
      )
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    if comment.save
      redirect_to "/posts/#{comment.post.id}",  notice: 'コメントを投稿しました。'
    else
      redirect_to "/posts/#{comment.post.id}",  notice: 'コメントを投稿できませんでした'
    end
  end

  def destroy
    comment = Comment.find(params[:post_id])
    comment.destroy
    redirect_to "/posts/#{comment.post.id}",  notice: 'コメントを削除しました。'
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/foreigns_controller.rb
class ForeignsController < ApplicationController
  def index
    @posts = Post.where(genre: 2).order("created_at DESC").page(params[:page]).per(20)
  end
end

app/controllers/inquirys_controller.rb
class InquirysController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, except: [:index, :show]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(12)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: '記事を投稿しました。' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: '記事を更新しました。' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: '記事を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :genre, :content).merge(user_id: current_user.id)
    end

    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @posts = Post.where(genre: 1).order("created_at DESC").page(params[:page]).per(20)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @posts = user.posts
    @comments = user.comments
  end
end

app/controllers/worrys_controller.rb
class WorrysController < ApplicationController
  def index
    @posts = Post.where(genre: 0).order("created_at DESC").page(params[:page]).per(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foreigns_helper.rb
module ForeignsHelper
end

app/helpers/inquirys_helper.rb
module InquirysHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/worrys_helper.rb
module WorrysHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_notifications.html.erb
<div class="notification">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: key %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KaigoBbs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="nav-box">
        <div class="nav-box__nav-left">
          <div class="nav-box__nav-left__nav-genre">
            <%= link_to root_path , class: 'navi-post', method: :get do %>
            <i class="fa fa-home fa-3x"></i>
            <% end %>
          </div>
          <div class="nav-box__nav-left__nav-genre">
            <%= link_to "介護お悩み掲示板", worrys_path , class: 'navi-post' %>
          </div>
          <div class="nav-box__nav-left__nav-genre">
            <%= link_to "スキルアップ・転職", skills_path, class: 'navi-post' %>
          </div>
          <div class="nav-box__nav-left__nav-genre">
            <%= link_to "技能実習生関連", foreigns_path, class: 'navi-post' %>
          </div>
        </div>

        <% if user_signed_in? %>
          <div class="nav-box__nav-right">
            <div class="nav-box__nav-right__nav-info">
              <%= link_to "新規投稿", new_post_path, class: 'right_side' %>
            </div>
            <div class="nav-box__nav-right__nav-info">
              <%= link_to "マイページ", "/users/#{current_user.id}", class: 'right_side' %>
            </div>
            <div class="nav-box__nav-right__nav-info">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'right_side' %>
            </div>
            <div class="nav-box__nav-right__nav-info">
              <%= link_to "お問い合わせ", inquirys_path, class: 'right_side' %>
            </div>
          </div>

        <% else %>
        <div class="nav-box__nav-right">
          <div class="nav-box__nav-right__nav-info">
            <%= link_to "新規登録", new_user_registration_path, class: 'right_side' %>
          </div>
          <div class="nav-box__nav-right__nav-info">
            <%= link_to "ログイン", new_user_session_path, class: 'right_side' %>
          </div>
          <div class="nav-box__nav-right__nav-info">
            <%= link_to "お問い合わせ", inquirys_path, class: 'right_side' %>
          </div>
          <div class="nav-box__nav-right__nav-info">
            <%= link_to "管理画面", "/admin", class: 'right_last' %>
          </div>
        </div>
        <% end %>
      </div>
    </header>

    <div class="main_contents">
      <%= render 'layouts/notifications'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_index.html.erb
<table class="table table-hover">
    <thead>
      <tr class="table-tr">
        <th class="table-tr__table-id">ID</th>
        <th class="table-tr__table-genre">ジャンル</th>
        <th class="table-tr__table-title">タイトル</th>
        <th class="table-tr__table-name">投稿者</th>
        <th class="table-tr__table-date">投稿日時</th>
      </tr>
    </thead>
    <tbody>
      <% posts.each do |post| %>
        <tr class="table-tr">
          <td class="table-tr__table-id"><%= post.id %></td>
          <td class="table-tr__table-genre"><%= post.genre_i18n %></td>
          <td class="table-tr__table-title"><%= link_to "#{post.title}", post %></td>
          <td class="table-tr__table-name"><%= post.user.nickname %></td>
          <td class="table-tr__table-date"><%= post.created_at.strftime("%Y/%m/%d %H:%M") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>